### ISSUE TITLE
Error in PDF?

### ISSUE THREAD

**Issue by paulvickers** [tstumm/asciidoctor-mathematical#7]
I ran the minimal example (sample.adoc) with the following command:
`asciidoctor-pdf -r asciidoctor-mathematical -a mathematical-format=svg -o testsvg.pdf sample.adoc`

The output file is:
[testsvg.pdf](https://github.com/tstumm/asciidoctor-mathematical/files/214813/testsvg.pdf)

The file opens fine in Apple's Preview, but if I try to open it in Adobe Acrobat on both OS X and Windows, the following error is reported on opening it:
> An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem.

The file then opens, but it only displayed as far as the first equation after which it is blank. When using the PNG output with 
`asciidoctor-pdf -r asciidoctor-mathematical -o test.pdf sample.adoc`
Acrobat opens and renders the file without problem.

I am running this on OS X 10.11.4. Can anyone else replicate this or is it just my set up?

**Comment by tstumm** [comment]
Sounds like a problem with asciidoctor-pdf (if the svg files are not corrupt due to mathematical).

**Comment by mojavelinux** [comment]
I'm pretty sure this is an issue with Asciidoctor PDF and therefore this issue can be closed. However, there isn't a single PDF reader on my machine that complains about this PDF. Therefore, I think the bug is actually in Acrobat Reader on OS X and Windows. This is a completely valid PDF file. It even works find on Acrobat Reader on Linux, which even further justifies my conclusion.

**Comment by ProgramFan** [comment]
Based on @mojavelinux's comment and my own experience, I think this issue can be closed. Please re-open it if there are new clues.
